### PR TITLE
Implement Configure getters and setters

### PR DESCRIPTION
**Pull request by peter-madigan**
Still fails the value validation tests, but I wasn't able to quickly figure out what is going wrong. That should be solved before merging.

### CODE REVIEW

**Comment by peter-madigan** [comment]
Fixed! Passes all tests.

**Comment by samkohn** [comment]
Thanks for fixing all the typos in my test code.

**Comment by peter-madigan** [comment]
No problem, also found out that bools are subclasses of ints in python, so `isinstance(True, int)` returns True.

**Comment by samkohn** [comment]
Could you rewrite the `type` tests to instead try type conversions? E.g.

```python
# instead of
if not type(channels) == list:
    raise ValueError()
# do
channels = list(channels)
map(int, channels)
# which will raise a ValueError or TypeError if there's a problem
```
I will rewrite the tests to check for any error rather than just a ValueError and post again here when it's pushed.

Also: not required, but you can replace the `value > 0 and value < 32` with `value in range(32)`. It reads more smoothly. You can also do for the binary values `value in [0, 1]`.

**Comment by samkohn** [comment]
Actually, I didn't think that through completely, particularly your observation that bool is a subclass of int. This code as written will more than suffice. I'll merge it tonight or tomorrow.

**Comment by peter-madigan** [comment]
I'll probably just leave the range validation as is, since some of the ranges are quite large (e.g. reset_cycles).

**Pull request merged**
