### PR TITLE
Clean up methods for Config read/write to JSON

### PR DESCRIPTION
**Pull request by peter-madigan**
Implements @samkohn's suggestion -- allows for config files to just specify values that are not default.

### CODE REVIEW

**Comment by samkohn** [comment]
Haha you beat me by 5 seconds to fixing that typo

**Comment by peter-madigan** [comment]
Forgot to run pytest before opening the PR. Oops

**Comment by samkohn** [comment]
Good ol' pytest

**Comment by samkohn** [comment]
Not sure that this append thing does what you want. You could end up with a file like this:

```python
{
    'setting_1': blah,
...
   'setting_n': blah
}
{
    'setting_n+1': blah,
}
```

Does the code handle that possibility?

**Comment by peter-madigan** [comment]
I was thinking that we could include both the configuration and the output
data in the same file, this might be misguided though. What do you think?

You're right that this is not quite right either way.

**Comment by samkohn** [comment]
I think the right way for what you want is to implement that in the Chip method for exporting the data. Since the Chip knows about its own configuration, it can call `self.config.to_dict()` and add the results to whatever it wants to save.

**Pull request merged**
